=encoding utf8

=head1 NAME

mbank-cli - (legacy) command-line interface to the on-line banking system of mBank

=head1 SYNOPSIS

=over 2

=item *
B<mbank-cli> [B<list>] [I<option>...]

=item *
B<mbank-cli> B<history> [I<option>...] [B<--range> I<start-date> I<end-date> | B<--from> I<start-date> [B<--to> I<end-date>] ] {I<account> | B<-M> I<account>...  | B<-A>}

=item *
B<mbank-cli> B<future> [I<option>...] {I<account> | B<-M> I<account>...  | B<-A>}

=item *
B<mbank-cli> B<blocked> [I<option>...] {I<account> | B<-M> I<account>...  | B<-A>}

=item *
B<mbank-cli> B<deposits> [I<option>...]

=item *
B<mbank-cli> B<funds> [I<option>...]

=item *
B<mbank-cli> B<notices> [I<option>...]

=item *
B<mbank-cli> B<rename> [I<option>...] I<account> I<new-name>

=item *
B<mbank-cli> B<logout> [I<option>...]

=item *
B<mbank-cli> B<void> [I<option>...]

=back

=head1 DESCRIPTION

B<mbank-cli> provides basic command-line interface to the online banking system of mBank.

This is the legacy version of B<mbank-cli>, which uses the web interface at
L<https://www.mbank.com.pl/>, which is in the process of being shut down.

=head2 Output format

Records are separated by newline (0x0A, LF) characters.
Each line contains fields separated by tab (0x09, HT) characters.

=head2 Common options

The following options are available for all commands:

=over 4

=item B<--verbose>

Display the debugging information.

=item B<--debug> I<debug-directory>

Save the debugging information (including dumps of downloaded pages) into I<debug-directory>.

=item B<--config> I<config-file>

Use I<config-file> as the configuration file.

The default is to use F<mbank-cli.conf> in the same directory as the
B<mbank-cli> script itself.

=item B<--cookie-jar> I<cookie-jar-file>

Use I<cookie-jar-file> to store state of the phony web browser.

The default is to use F<cookie-jar.txt> in the same directory as the
B<mbank-cli> script itself.

=back

=head2 Selecting accounts

Some commands (B<history>, B<future>, B<blocked>) can act on one or more accounts.
They can be selected in the following ways:

=over 4

=item I<account-name> (as a positional argument)

select a single account

=item B<-M>, B<--multiple-accounts> I<account>...

select multiple accounts

=item B<-A>, B<--all-accounts>

select all accounts

=back

The “B<*>” character can be used as a wildcard character.

=head2 The “list” command

Syntax:
B<mbank-cli> [B<list>] [I<option>...]

For each account, print:

=over 4

=item Z<>

I<account-name> I<account-number> I<balance> I<avail-resources>

=back

=head2 The “history” command

Syntax:
B<mbank-cli> B<history> [I<option>...] [B<--range> I<start-date> I<end-date> | B<--from> I<start-date> [B<--to> I<end-date>] ] {I<account> | B<-M> I<account>...  | B<-A>}

Print the history of the selected account(s),
in the following format:

=over 4

=item Z<>

I<[account-name]> I<date> I<accounting-date> I<amount> I<balance> I<description>

=back

Newline characters in I<description> are replaced by tab characters.

Time range can be selected with the following options:

=over 4

=item B<--from> I<start-date>

Show operations with the date not before I<start-date>.

=item B<--range> I<start-date> I<end-date>, B<--from> I<start-date> B<--to> I<end-date>

Show operations with the date between I<start-date> and I<end-date>, inclusive.

=back

A date is either “B<now>” or in the I<YYYY>-I<MM>-I<DD> format.

=head2 The “future” command

Syntax:
B<mbank-cli> B<future> [I<option>...] {I<account> | B<-M> I<account>...  | B<-A>}

Print the list of planned operations for the selected account(s),
in the following format:

=over 4

=item Z<>

I<[account-name]> I<date> I<recipient> I<title> I<amount> I<status>

=back

=head2 The “blocked” command

Syntax:
B<mbank-cli> B<blocked> [I<option>...] {I<account> | B<-M> I<account>...  | B<-A>}

Print the list of operations that were carried out but not booked,
in the following format:

=over 4

=item Z<>

I<[account-name]> I<registration-date> I<finalization-date> I<amount> I<title>

=back

=head2 The “deposits” command

Syntax:
B<mbank-cli> B<deposits> [I<option>...]

Print the list of time deposits,
in the following format:

=over 4

=item Z<>

I<deposit-name> I<establishment-date> I<maturity-date> I<term> I<interest> I<status> I<amount>

=back

=head2 The “funds” command

Syntax:
B<mbank-cli> B<funds> [I<option>...]

Print the list of investment funds,
in the following format:

=over 4

=item Z<>

I<fund-name> I<amount>

=back

=head2 The “notices” command

Syntax:
B<mbank-cli> B<notices> [I<option>...]

Print the list of notices,
in the following format:

=over 4

=item Z<>

I<new> I<date> I<title>

=back

I<new> is either “B<N>” (for an unread notice) or an empty string (otherwise).

=head2 The “rename” command

Syntax:
B<mbank-cli> B<rename> [I<option>...] I<account> I<new-name>

Change the account name.

=head2 The “logout” command

Syntax:
B<mbank-cli> B<logout> [I<option>...]

Log out from the web interface.

=head2 The “void” command.

Syntax:
B<mbank-cli> B<void> [I<option>...]

Do (almost) nothing. This is only useful only for the debugging purposes.

=head1 EXIT STATUS

=over 4

=item Z<>0

Success.

=item Z<>1

Failure because of a user error.

=item Z<>2

Failure because of an HTTP error. This may be due to a network error, but might as well be a result of an API error (see below).

=item Z<>3

Failure because of an unexpected behaviour of the web interface (so called “API error”). If you encounter this, please file a bug at the L<issue tracker|https://code.google.com/p/mbank‐cli/issues/list>.

=back

=head1 FILES

By default, B<mbank-cli> looks for the configuration and state files in the
directory as the B<mbank-cli> script itself.

=over 4

=item F<mbank-cli.conf>

The default configuration file.

An alternative configuration
can be specified using the B<--config> option.

To create the configuration file, use the following command:

    $ umask 077
    $ cat <<EOF | gpg --armor --encrypt --default-recipient-self > mbank-cli.conf
    Login 123456
    Password "your-password"
    EOF

Encrypting the configuration file with GnuPG is optional, but highly recommended.

=item F<cookie-jar.txt>

State of the phony web browser.

An alternative location of the cookie jar
can be specified using the B<--cookie-jar> option.

=back

=head1 EXAMPLES

    $ ./mbank-cli list  # list accounts

    $ ./mbank-cli history eKonto  # print history of the “eKonto” account

    $ ./mbank-cli history eKonto --range 2005-01-01 2005-12-31

    $ ./mbank-cli history eKonto --from 2006-06-01

    $ ./mbank-cli future eMax  # print planned operations for the “eMax” account

    $ ./mbank-cli rename 'eMax - foo' 'bar'  # from now on, it will be called “eMax - bar”

    $ ./mbank-cli funds  # list investment funds

    $ ./mbank-cli logout

=head1 SEE ALSO

L<gpg(1)>
