#!/bin/sh

# Copyright © 2009-2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
cd "${0%/*}/.."
if [ $# -ge 2 ]
then
    printf '%s [commit]\n' "$0" >&2
    exit 1
fi
if ! [ -d .git ]
then
    printf '%s requires git checkout\n' "$0" >&2
    exit 1
fi
pwd="$PWD"
commit=${1:-HEAD}
commit=$(git describe "$commit")
name=$(git cat-file blob "$commit:doc/NEWS" | head -n1 | cut -d ' ' -f 1)
date=$(git rev-list -1 --format=%cI "$commit" | grep -o '^....-..-..' | tr -d -)
version=$(git cat-file blob "$commit:doc/NEWS" | head -n1 | cut -d ' ' -f2 | tr -d '()')
released=$(git cat-file blob "$commit:doc/NEWS" | head -n1 | grep -v -w UNRELEASED || true)
[ -n "$released" ] || version="${version}rc${date}"
printf 'Commit: %s\nVersion: %s\n' "$commit" "$version" >&2
set -x
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
tar_opts='--owner=root --group=root --mode=u=rwX,go=rX --format=ustar --sort=name'
gzip='gzip -9 -n'
git archive "$commit" --prefix="$name-$version/" | tar -C "$sourceroot" -xf -
cd "$sourceroot"/*
rm -r .git*
rm .mailmap
rm README.rst  # shipped as doc/README
mv LICENSE doc/
make -C doc/
make -C t/certs/
rm t/certs/*.tmp.cnf
rm private/build-source-tarball
find . -empty -delete
cd ..
mkdir -p "$pwd/dist"
tar $tar_opts -I "$gzip" -cf "$pwd/dist/$name-$version.tar.gz" */
rm -r "$sourceroot"
set +x
cd "$pwd"
ls -d "dist/$name-$version.tar.gz"

# vim:ts=4 sts=4 sw=4 et
