#!/bin/sh

# Copyright © 2009-2015 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ $# -ge 2 ]
then
    printf '%s [revision]\n' "$0" >&2
    exit 1
fi
set -e -x
pwd="$PWD"
revision="${1:-tip}"
name=$(hg cat -r "$revision" doc/NEWS | head -n1 | cut -d ' ' -f 1)
date=$(hg log -r "$revision" --template='{date|isodate}' | head -c 10 | tr -d -)
version=$(hg cat -r "$revision" doc/NEWS | head -n1 | cut -d ' ' -f2 | tr -d '()')
released=$(hg cat -r "$revision" doc/NEWS | head -n1 | grep -v -w UNRELEASED || true)
[ -n "$released" ] || version="${version}rc${date}"
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
export TAR_OPTIONS='--owner root --group root --mode a+rX --format ustar'
export GZIP='-9 -n'
mkdir -p "$sourceroot/$name-$version"
hg archive -r "$revision" "$sourceroot/$name-$version"
cd "$sourceroot"
prename -v 's/[.]rst$//' $name-*/doc/*.rst
make -C $name-*/doc
make -C $name-*/t/certs/
rm -rf $name-*/private/
rm -rf */.hg*
rm -rf */.travis*
find $name-*/ -empty -delete
tar -czf "$pwd/$name-$version.tar.gz" */
rm -rf "$sourceroot"

# vim:ts=4 sts=4 sw=4 et
