#!/bin/sh
set -e -u

export LC_ALL=C

global_exclude='::RequireRcsKeywords'
tests_exclude='::(RequireCarping|ProhibitAutomaticExportation|ProhibitComplexRegexes|RequireEndWithOne|RequireExplicitPackage)'

private_exclude='::(RequireCarping|RequireEndWithOne|RequireExplicitPackage)'
private_perl=$(grep -l '^#.*[ /]perl' private/*)

here=$(basename "$0")
cd "$here/.."

sed -n -r -e '/^\[-?/ { s///; s/\]$//; p }' .perlcriticrc \
| sort -c

target=$(mktemp -t mbank-cli.perlcritic.XXXXXX)

run_perlcritic()
{
    perlcritic --exclude "$global_exclude" "$@" >> "$target" && return
    rc=$?
    [ $rc -eq 2 ] || exit $rc
}

run_perlcritic "$@" mbank-cli
run_perlcritic "$@" \
    --exclude "$tests_exclude" \
    t/*.t t/*.pm
run_perlcritic "$@" \
    --exclude "$private_exclude" \
    $private_perl
rc=0
grep -v ' source OK$' "$target" && rc=1
rm -f "$target"
exit $rc

# vim:ts=4 sts=4 sw=4 et
