#!/bin/sh
set -e -u
here=$(basename "$0")
cd "$here/.."
target=doc/todo.perlcritic

run_perlcritic()
{
    perlcritic --verbose '%p\n' "$@" >> "${target}.tmp" && return
    rc=$?
    if [ $rc -ne 2 ]
    then
        rm -f "${target}.tmp"
        exit $rc
    fi
}

: > "$target.tmp"
run_perlcritic mbank-cli
run_perlcritic \
    --exclude '::(RequireCarping|ProhibitAutomaticExportation|RequireVersionVar)' \
    t/*.t t/*.pm
sort "${target}.tmp" \
| grep -v ' source OK$' \
| uniq -c > "${target}.new"
rm -f "${target}.tmp"
diff -u "${target}" "${target}.new" || true
mv "${target}.new" "${target}"

# vim:ts=4 sw=4 et
