#!/bin/sh
set -e -u
here=$(basename "$0")
cd "$here/.."
target=doc/todo.perlcritic
if perlcritic --verbose '%p\n' mbank-cli > "${target}.tmp"
then
    :
else
    rc=$?
    if [ $rc -ne 2 ]
    then
        rm -f "${target}.tmp"
        exit $rc
    fi
fi
sort "${target}.tmp" | uniq -c > "${target}.new"
rm -f "${target}.tmp"
diff -u "${target}" "${target}.new" || true
mv "${target}.new" "${target}"

# vim:ts=4 sw=4 et
